# # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#   ╔╦╗╦═╗╔═╗╦  ╦╦╔═╗ ┬ ┬┌┬┐┬                           #
#    ║ ╠╦╝╠═╣╚╗╔╝║╚═╗ └┬┘││││                           #
#  o ╩ ╩╚═╩ ╩ ╚╝ ╩╚═╝o ┴ ┴ ┴┴─┘                         #
#                                                       #
# This file configures Travis CI.                       #
# (i.e. how we run the tests... mainly)                 #
#                                                       #
# https://docs.travis-ci.com/user/customizing-the-build #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # #

language: node_js

dist: trusty
sudo: required

node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"
  - "7"
  - "node"

branches:
  only:
    - master

notifications:
  email:
    - daniel.rataj@centrum.cz

addons:
  sonarcloud:
    organization: "danielrataj-github"
    token:
      secure: "$SONAR_TOKEN"
script:
  - sonar-scanner

jdk:
  - oraclejdk8

cache:
  directories:
    - "$HOME/.sonar/cache"
